import {PracticeProblem} from "@/types/lesson";
const io=(id:string,title:string,statement:string,starterCode:string,testInput:string,expectedOutput:string,explanation:string):PracticeProblem=>({id,title,statement,inputFormat:"Values are supplied on standard input as described in the statement.",outputFormat:"Print exactly the requested result.",constraints:["Inputs fit in Python integers","Do not print prompts or labels unless requested"],hint:"Start by parsing the input, compute the result, then print only the answer.",starterCode,testInput,expectedOutput,explanation,complexity:{time:"O(n) or better",space:"O(n) or better"},commonMistakes:["Printing an input prompt","Reading the wrong number of lines","Adding extra output"]});
export const ioProblems:PracticeProblem[]=[
io("s2-double","Double each test case","Read t, then t integers. Print twice each integer.","def solve():\n    # Read input and print answers\n    pass\n\nsolve()","3\n5\n10\n20\n","10\n20\n40","Loop exactly t times and print one result per line."),
io("s2-sum","Sum an array","Read n and a line of n integers. Print their sum.","def solve():\n    pass\n\nsolve()","5\n1 2 3 4 5\n","15","Parse the second line with split and map."),
io("s2-pair","Add two values","Read two space-separated integers and print their sum.","def solve():\n    pass\n\nsolve()","12 30\n","42","Unpack the two parsed values."),
io("s2-max","Maximum value","Read n and n integers. Print the maximum.","def solve():\n    pass\n\nsolve()","4\n-2 8 3 1\n","8","The first value is a count, not part of the array."),
io("s2-lines","Uppercase lines","Read t, then print each following line in uppercase.","def solve():\n    pass\n\nsolve()","2\nhello world\njudge ready\n","HELLO WORLD\nJUDGE READY","Preserve spaces inside each line."),
io("s2-readall","Read all numbers","Using sys.stdin.read, print the sum of every integer.","import sys\n\ndef solve():\n    pass\n\nsolve()","1 2\n3 4 5\n","15","Split the entire input regardless of line boundaries.")];
export const arrayProblems:PracticeProblem[]=[
{id:"lc189",title:"LC 189 - Rotate Array",statement:"Rotate nums to the right by k steps, modifying the list in-place.",inputFormat:"Line 1: space-separated integers. Line 2: k.",outputFormat:"Print the rotated list as space-separated integers.",constraints:["1 <= len(nums) <= 100000","0 <= k <= 100000"],hint:"Normalize k, reverse all values, then reverse the two partitions.",starterCode:"def rotate(nums, k):\n    # Implement the O(n), O(1) reversal method\n    pass\n\nnums = list(map(int, input().split()))\nk = int(input())\nrotate(nums, k)\nprint(*nums)",testInput:"1 2 3 4 5 6 7\n3\n",expectedOutput:"5 6 7 1 2 3 4",explanation:"After reversing everything, the desired suffix is in front but reversed. Reverse each partition to restore order.",complexity:{time:"O(n)",space:"O(1)"},commonMistakes:["Forgetting k %= n","Using nums = ... instead of modifying nums[:]","Not handling an empty list"]},
{id:"lc26",title:"LC 26 - Remove Duplicates",statement:"Remove duplicates from a sorted array in-place. Return k and keep unique values in nums[:k].",inputFormat:"One line of sorted space-separated integers.",outputFormat:"Print k, then print the first k elements.",constraints:["1 <= len(nums) <= 30000","nums is sorted"],hint:"slow marks the last unique value; fast scans candidates.",starterCode:"def remove_duplicates(nums):\n    # Implement the two-pointer method\n    pass\n\nnums = list(map(int, input().split()))\nk = remove_duplicates(nums)\nprint(k)\nprint(nums[:k])",testInput:"1 1 2 2 3\n",expectedOutput:"3\n[1, 2, 3]",explanation:"Every new value is written immediately after the last unique value. Elements beyond k are irrelevant.",complexity:{time:"O(n)",space:"O(1)"},commonMistakes:["Comparing with the wrong pointer","Returning the list instead of k","Allocating a set, which breaks the in-place goal"]}];
